### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by mehcode** [izik1/gbops#10]
- [x] Single-click to pop-up with hover
 - [x] user-select: none
 - [x] Make colorization be a 5px left border
 - [x] 8px padding minimum everywhere
 - [ ] Freeze header row/col and scroll content

**Comment by izik1** [comment]
:+1: I'll work on this when I've both remembered it and am not tired >.>

**Comment by izik1** [comment]
Colorization has potential improvements with a semi-transparent background, more research is needed for freezing rows.

**Comment by izik1** [comment]
I am _pretty_ sure this could've been closed over a year ago, oops.
