### ISSUE TITLE
`stop` is 1 byte instruction, not 2

### ISSUE THREAD

**Issue by binji** [izik1/gbops#3]

**Comment by izik1** [comment]
I can't remember if it's supposed to be 2, mostly because I don't think anything uses it. Going to put it at 2 anyway though.

**Comment by JL2210** [comment]
STOP is two bytes. The first is (obviously) 0x10, and the second is required to be 0x00. If it is not, the processor freezes like it does when running an invalid opcode.

**Comment by JL2210** [comment]
Just close this. `stop` is two bytes long.

**Comment by jverkoey** [comment]
FWIW, RGBDS appears to always encode STOP as a two byte instruction:

https://github.com/gbdev/rgbds/blob/77279984a53054436450ea251343515bfdbf25b1/src/asm/parser.y#L1865-L1868

```y
z80_stop	: T_Z80_STOP {
			out_AbsByte(0x10);
			out_AbsByte(0x00);
		}
```

**Comment by wordandahalf** [comment]
According to the official Gameboy Development Manual from Nintendo (https://ia803208.us.archive.org/9/items/GameBoyProgManVer1.1/GameBoyProgManVer1.1.pdf, page 124), STOP is encoded as 0x10 followed by 0x00.

**Comment by izik1** [comment]
I was about to close this as "unless anyone has evidence to the contrary", but then I remembered something (also helped that I looked at other documentation, including my own emulators). Like HALT has the halt bug (a failure to increment PC for one instruction(? cycle?) after _not_ halting, STOP has its own bug, which is poetically the inverse, it *skips* a byte, which means that it _is_ technically one byte, errata are weird.

**Comment by izik1** [comment]
(fixed)

**Comment by Lokathor** [comment]
I was told recently that STOP, despite being 1 byte itself, will cause the very next byte to be executed *or not* depending on various factors. So, while it's true that STOP is 1 byte, it should always be followed by the 0x00, in case the second byte ends up being executed.

![image](https://user-images.githubusercontent.com/5456384/185814387-0d32724d-45df-4349-b8d1-2727474a4e49.png)
